# Generated by Django 4.1.3 on 2022-11-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_user"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
